(defun bubble-step (lst last-swap)
  (cond ((or (null lst) (null (cdr lst))) (values lst last-swap))
        (t (let ((a (car lst))
                 (b (cadr lst)))
             (if (> a b)
                 (let* ((swapped (cons b (cons a (cddr lst)))))
                   (multiple-value-bind (sorted-lst new-last-swap)
                       (bubble-step (cdr swapped) t)
                     (values (cons (car swapped) sorted-lst)
                             (or new-last-swap t))))
                 (multiple-value-bind (sorted-lst new-last-swap)
                     (bubble-step (cdr lst) nil)
                   (values (cons a sorted-lst)
                           (or new-last-swap last-swap))))))))

(defun recursive-bubble-sort (lst)
  (labels ((recursive-sort (lst)
             (multiple-value-bind (new-lst last-swap)
                 (bubble-step lst nil)
               (if last-swap
                   (recursive-sort new-lst)
                   new-lst))))
    (recursive-sort lst)))

(defun check-sort-func (test-name input expected)
  (let ((result (recursive-bubble-sort input)))
    (if (equal result expected)
        (format t "~a passed: ~a -> ~a~%" test-name input result)
        (format t "~a failed: ~a -> ~a~%" test-name input result))))

(defun test-sort-func ()
  (check-sort-func "Test 1" '(4 3 2 1) '(1 2 3 4))
  (check-sort-func "Test 2" '(1 2 3 4) '(1 2 3 4))
  (check-sort-func "Test 3" '(5 1 3 2 4) '(1 2 3 4 5)))

(defun sort-imp (lst)
  (let ((R (- (length lst) 1))
        k)
    (loop while (> R 0) do
      (setf k 0)
      (loop for i from 0 below R do
        (when (> (nth i lst) (nth (+ i 1) lst))
          (let ((tmp (nth i lst)))
            (setf (nth i lst) (nth (+ i 1) lst))
            (setf (nth (+ i 1) lst) tmp)
            (setf k i))))
      (setf R k))
    lst))

(defun check-sort-imp (test-name input expected)
  (let ((result (sort-imp (copy-list input))))
    (if (equal result expected)
        (format t "~a passed: ~a -> ~a~%" test-name input result)
        (format t "~a failed: ~a -> ~a~%" test-name input result))))

(defun test-sort-imp ()
  (check-sort-imp "Test 1" '(4 3 2 1) '(1 2 3 4))
  (check-sort-imp "Test 2" '(1 2 3 4) '(1 2 3 4))
  (check-sort-imp "Test 3" '(5 1 3 2 4) '(1 2 3 4 5)))
